<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: app/Proto/ticket.proto

namespace GRPC\Services\Ticket;

use Spiral\RoadRunner\GRPC;

interface TicketInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "microtix.Ticket";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetTicketRequest $in
    * @return TicketData
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function getTicket(GRPC\ContextInterface $ctx, GetTicketRequest $in): TicketData;
}
