<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/Proto/event.proto

namespace GRPC\Services\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>microtix.EventInstance</code>
 */
class EventInstance extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.microtix.EventData eventData = 2;</code>
     */
    protected $eventData = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type \GRPC\Services\Event\EventData $eventData
     * }
     */
    public function __construct($data = NULL) {
        \GRPC\Services\Event\Meta\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.microtix.EventData eventData = 2;</code>
     * @return \GRPC\Services\Event\EventData
     */
    public function getEventData()
    {
        return $this->eventData;
    }

    /**
     * Generated from protobuf field <code>.microtix.EventData eventData = 2;</code>
     * @param \GRPC\Services\Event\EventData $var
     * @return $this
     */
    public function setEventData($var)
    {
        GPBUtil::checkMessage($var, \GRPC\Services\Event\EventData::class);
        $this->eventData = $var;

        return $this;
    }

}

