<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/Proto/notification.proto

namespace GRPC\Services\Notification;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>microtix.NotificationEventData</code>
 */
class NotificationEventData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 organizer_id = 2;</code>
     */
    protected $organizer_id = 0;
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string startTime = 4;</code>
     */
    protected $startTime = '';
    /**
     * Generated from protobuf field <code>string endTime = 5;</code>
     */
    protected $endTime = '';
    /**
     * Generated from protobuf field <code>string address = 6;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>string ticketPrice = 7;</code>
     */
    protected $ticketPrice = '';
    /**
     * Generated from protobuf field <code>string discount = 8;</code>
     */
    protected $discount = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $organizer_id
     *     @type string $description
     *     @type string $startTime
     *     @type string $endTime
     *     @type string $address
     *     @type string $ticketPrice
     *     @type string $discount
     * }
     */
    public function __construct($data = NULL) {
        \GRPC\Services\Notification\Meta\Notification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 organizer_id = 2;</code>
     * @return int
     */
    public function getOrganizerId()
    {
        return $this->organizer_id;
    }

    /**
     * Generated from protobuf field <code>int32 organizer_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrganizerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->organizer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string startTime = 4;</code>
     * @return string
     */
    public function getStartTime()
    {
        return $this->startTime;
    }

    /**
     * Generated from protobuf field <code>string startTime = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->startTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string endTime = 5;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->endTime;
    }

    /**
     * Generated from protobuf field <code>string endTime = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->endTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 6;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ticketPrice = 7;</code>
     * @return string
     */
    public function getTicketPrice()
    {
        return $this->ticketPrice;
    }

    /**
     * Generated from protobuf field <code>string ticketPrice = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTicketPrice($var)
    {
        GPBUtil::checkString($var, True);
        $this->ticketPrice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string discount = 8;</code>
     * @return string
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * Generated from protobuf field <code>string discount = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDiscount($var)
    {
        GPBUtil::checkString($var, True);
        $this->discount = $var;

        return $this;
    }

}

