<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/Proto/notification.proto

namespace GRPC\Services\Notification;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>microtix.NotificationNothing</code>
 */
class NotificationNothing extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GRPC\Services\Notification\Meta\Notification::initOnce();
        parent::__construct($data);
    }

}

