<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: app/Proto/notification.proto

namespace GRPC\Services\Notification;

use Spiral\RoadRunner\GRPC;

interface NotificationInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "microtix.Notification";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param TransactionData $in
    * @return \Google\Protobuf\GPBEmpty
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function addTransaction(GRPC\ContextInterface $ctx, TransactionData $in): \Google\Protobuf\GPBEmpty;
}
