<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/Proto/notification.proto

namespace GRPC\Services\Notification\Meta;

class Notification
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afa010a1c6170702f50726f746f2f6e6f74696669636174696f6e2e70726f746f12086d6963726f74697822320a0f5472616e73616374696f6e4461746112100a086576656e745f6964180120012805120d0a05656d61696c18022001280932530a0c4e6f74696669636174696f6e12430a0e6164645472616e73616374696f6e12192e6d6963726f7469782e5472616e73616374696f6e446174611a162e676f6f676c652e70726f746f6275662e456d707479423fca021a475250435c53657276696365735c4e6f74696669636174696f6ee2021f475250435c53657276696365735c4e6f74696669636174696f6e5c4d657461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

