<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: app/Proto/payment.proto

namespace GRPC\Services\Payment;

use Spiral\RoadRunner\GRPC;

interface PaymentInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "microtix.Payment";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param PaymentInfo $in
    * @return Status
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function pay(GRPC\ContextInterface $ctx, PaymentInfo $in): Status;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param PaymentId $in
    * @return Status
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function checkStatus(GRPC\ContextInterface $ctx, PaymentId $in): Status;
}
